export const GET_PROJECTS_PENDING = 'GET_PROJECTS_PENDING';
export const GET_PROJECTS_FULFILLED = 'GET_PROJECTS_FULFILLED';
export const GET_PROJECTS_REJECTED = 'GET_PROJECTS_REJECTED';

export const GET_PROJECT_PENDING = 'GET_PROJECT_PENDING';
export const GET_PROJECT_FULFILLED = 'GET_PROJECT_FULFILLED';
export const GET_PROJECT_REJECTED = 'GET_PROJECT_REJECTED';

export const CREATE_PROJECT_PENDING = 'CREATE_PROJECT_PENDING';
export const CREATE_PROJECT_FULFILLED = 'CREATE_PROJECT_FULFILLED';
export const CREATE_PROJECT_REJECTED = 'CREATE_PROJECT_REJECTED';

export const CREATE_MEMBER_PENDING = 'CREATE_MEMBER_PENDING';
export const CREATE_MEMBER_FULFILLED = 'CREATE_MEMBER_FULFILLED';
export const CREATE_MEMBER_REJECTED = 'CREATE_MEMBER_REJECTED';

export const CREATE_EXPENSE_PENDING = 'CREATE_EXPENSE_PENDING';
export const CREATE_EXPENSE_FULFILLED = 'CREATE_EXPENSE_FULFILLED';
export const CREATE_EXPENSE_REJECTED = 'CREATE_EXPENSE_REJECTED';

export const RESET_PROJECT = 'RESET_PROJECT';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
