export const GET_PROJECT = 'GET_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const RESET_PROJECT = 'RESET_PROJECT';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';
