export const GET_PROJECTS_PENDING = 'GET_PROJECTS_PENDING';
export const GET_PROJECTS_FULFILLED = 'GET_PROJECTS_FULFILLED';
export const GET_PROJECTS_REJECTED = 'GET_PROJECTS_REJECTED';

export const GET_PROJECT_PENDING = 'GET_PROJECT_PENDING';
export const GET_PROJECT_FULFILLED = 'GET_PROJECT_FULFILLED';
export const GET_PROJECT_REJECTED = 'GET_PROJECT_REJECTED';

export const ADD_PROJECT_PENDING = 'ADD_PROJECT_PENDING';
export const ADD_PROJECT_FULFILLED = 'ADD_PROJECT_FULFILLED';
export const ADD_PROJECT_REJECTED = 'ADD_PROJECT_REJECTED';

export const RESET_PROJECT = 'RESET_PROJECT';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
