#!/bin/sh

# Spins up the development database in a Docker container

URI=$(./scripts/db-uri);
DB=$URI/autokitty

docker run -d -t -p 5984:5984 --name autokitty klaemo/couchdb:1.6.1

# Wait until the CouchDB process starts responding to HTTP requests before continuing

until $(curl --output /dev/null --silent --head --fail $URI); do
    sleep 1
done

# Create the autokitty database

curl -X PUT $DB

# Insert the design document and fixtures

DB=$DB npm run db:design-doc
DB=$DB npm run db:fixtures
